### ISSUE TITLE
Metadata collection

### ISSUE THREAD

**Issue by sanderfoobar** [comet-ml/kangas#122]
Kangas, by default on each startup, sends metadata to Comet:

- OS version
- Kernel information
- Python / Node version

Basically metadata collection concealed as version check. A real version check would e.g use the Github API to fetch the latest tag.

https://github.com/comet-ml/kangas/blob/df0c1a495032cc4f1c367c74fcb0ef6e5a2063be/backend/kangas/utils.py#L124-L149

**Comment by dsblank** [comment]
@sanderfoobar would you be willing to make a PR to optionally allow to use github API for version check? We can use the environment variable "KANGAS_VERSION_CHECK" if the value is something like "GITHUB_API".

BTW, this isn't meant to be concealed but it is meant to do two things: log the details, and check for version update. Logging the details does keep the user anonymous, but allows us to know what is working and what isn't (eg usage). Feel free to make a PR for code or docs to make this more clear.
