### ISSUE TITLE
Cannot run dg.show() in jupyter notebook

### ISSUE THREAD

**Issue by Khaihuyennguyen** [comet-ml/kangas#123]
Hi,

When I try to run these scripts in Google Colab

`import kangas as kg
`
`# Load an existing DataGrid
dg = kg.read_datagrid("https://github.com/caleb-kaiser/kangas_examples/raw/master/coco-500.datagrid.zip")`

`dg.show()`

![image](https://github.com/comet-ml/kangas/assets/50721063/db3c658f-2624-4f8a-b09a-727a9972202d)

The UI run as expected. However, when I tried to run in Jupyter envonment, it show nothing but a black background.

Do you happen to know which caused this issue??

Khai Nguyen

**Comment by dsblank** [comment]
@Khaihuyennguyen It looks like the above image is in a Jupyter environment. What is different about where it doesn't work?

BTW, sometimes it might be necessary to run at the console before running in Jupyter:

```
kangas server --terminate
```

**Comment by Khaihuyennguyen** [comment]
> @Khaihuyennguyen It looks like the above image is in a Jupyter environment. What is different about where it doesn't work?
> 
> BTW, sometimes it might be necessary to run at the console before running in Jupyter:
> 
> ```
> kangas server --terminate
> ```

The picture I attached when I tested on my google colab notebook which works fine. The problem is in Jupiter notebook from my company's conda environment. 

I ternimated all the servers as instructed but it stills show the black screen afterward

**Comment by Khaihuyennguyen** [comment]
Hi,

I figured out the problem. I remotely run the script on visual studio code from Ada in my local computer, so it is not syncing the output.

It is fixed when I run it inside Ada.

Thanks

**Comment by dsblank** [comment]
Thanks for posting your solution! Consider giving the project a star, and tell your friends :)

Also, let us know if you do anything interesting with Kangas.
