### ISSUE TITLE
Ability to display more than 10 rows in datagrid.show()?

### ISSUE THREAD

**Issue by jackperkins98** [comet-ml/kangas#124]
Hello! Myself and some others are interested in using kangas for image modeling projects. Is there a way to display more rows in the datagrid.show() UI without flipping pages? The page flips are quick but some of us would prefer to scroll longer, especially when reviewing many images for long periods. Thanks!

**Comment by dsblank** [comment]
@jackperkins98 Yes, you can. You can add `?rows=15` to show 15 rows. Be careful that you don't show too many.... it can have a bad effect on performance.

Let us know if that works for you.

**Comment by dsblank** [comment]
With show() you can add `datagrid.show(rows=15)`

**Comment by jackperkins98** [comment]
Perfect! Thank you.

**Comment by jackperkins98** [comment]
Sorry to reopen - is there also a similar option for launching from the command line? Thanks.

**Comment by dsblank** [comment]
No problem! Are you working from your own cloned copy of this repo, or using the pip-installed version?

If clone, then here is a PR to do what you request: https://github.com/comet-ml/kangas/pull/125

**Comment by jackperkins98** [comment]
Pip installed version, but I can set up repo access. I will try this branch, thanks!
