### ISSUE TITLE
Auto-resize or widen individual image viewer

### ISSUE THREAD

**Issue by julie-puckett** [comet-ml/kangas#126]
From the front end, when I click on an individual image to view it close-up and zoom, I sometimes need to scroll left-right or up-down to see the whole zoomed-in image.

Is there a way to auto-resize when I zoom so that I don't need to scroll? Or to make the viewer window taller and wider?

**Comment by dsblank** [comment]
Can you paste a short video (animated gif) showing what you see? What are the dimensions of the image that is misbehaving?
