### ISSUE TITLE
object of type Progressbar has no len()

### ISSUE THREAD

**Issue by fnauman** [comet-ml/kangas#84]
Thanks for the great library.

I installed kangas using:
```
pip install kangas
```

I then tried running the tutorial: [Integrations.ipynb](https://github.com/comet-ml/kangas/blob/main/notebooks/Integrations.ipynb)

When I run:

```python
dg = kg.read_dataframe(df)
```

I get the following error:

![image](https://user-images.githubusercontent.com/8434564/229184757-e9be9b8f-5db1-480d-b398-0a62cd721232.png)

I am using version: `2.2.4`.

Any ideas on how to solve this?

**Comment by dsblank** [comment]
Hmmm... can you try:

```python
pip install tqdm
```

To see if that helps?

**Comment by dsblank** [comment]
I have confirmed that this is an issue in Kangas, and will be fixed on the next release. Installing tqdm is a workaround for the moment.

Thanks @fnauman for reporting! Let us know if you are doing interesting things with Kangas. We'd love to hear about it!

**Comment by dsblank** [comment]
Pushed out a new version of Kangas, version 2.2.5, with changes that should address the issue.

**Comment by fnauman** [comment]
Thanks, that solved it!
