### ISSUE TITLE
Page number doesn't change

### ISSUE THREAD

**Issue by dsblank** [comet-ml/kangas#9]
Looks like this fix broke the paging: https://github.com/comet-ml/kangas/commit/0d96e1afa1996835248e78434c2625f305d84624

To reproduce:

1. Go to https://kangas.comet.com/
2. Select any datagrid
3. Click on the "next page" ">" button
4. The page number doesn't change

**Comment by caleb-kaiser** [comment]
Fixed by https://github.com/comet-ml/kangas/commit/0ed326e066a75a35fdb257cf31b30dae23f035d1
